services:
  workspace:
    build:
      context: ./docker/workspace
    container_name: laravel_workspace
    working_dir: /var/www/html
    volumes:
      - ./projects/${PROJECT_NAME}:/var/www/html
      - ./container/${PROJECT_NAME}/app/storage:/var/www/html/storage
      - ./container/${PROJECT_NAME}/app/bootstrap/cache:/var/www/html/bootstrap/cache
    tty: true
    depends_on:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  app:
    build:
      context: ./docker/app
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - ./projects/${PROJECT_NAME}:/var/www/html
      - ./container/${PROJECT_NAME}/app/storage:/var/www/html/storage
      - ./container/${PROJECT_NAME}/app/bootstrap/cache:/var/www/html/bootstrap/cache
    working_dir: /var/www/html
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public

  db:
    image: ${DB_IMAGE}
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-}
      MYSQL_USER: ${MYSQL_USER:-}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-}
      POSTGRES_DB: ${POSTGRES_DB:-}
      POSTGRES_USER: ${POSTGRES_USER:-}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-}
    volumes:
      - db_data:${DB_VOLUME_PATH}

volumes:
  db_data:
    name: ${DB_VOLUME_NAME}